project_name: Marine Surface Debris Detection System

dataset:
  root: "C:/Users/AlgoQuant-HR-Admin/Downloads/5151941"
  # If your dataset is already in YOLO format, set this to true.
  yolo_format: true
  # Optional: class names for detection
  classes: ["debris"]

preprocess:
  image_exts: [".jpg", ".jpeg", ".png"]
  val_ratio: 0.15
  test_ratio: 0.15
  seed: 42

training:
  framework: yolo # options: yolo, tf-classifier
  model: yolov8n.pt
  epochs: 50
  imgsz: 640
  batch: 16
  workers: 4
  device: auto

paths:
  processed_dir: data/processed
  splits_dir: data/splits
  models_dir: models
  runs_dir: runs

inference:
  conf: 0.25
  iou: 0.45

ui:
  map_tiles: "OpenStreetMap"



